### ISSUE TITLE
torch.cuda.OutOfMemoryError when quantize  LLaMa7B and LLaMa13B

### ISSUE THREAD

**Issue by wenqf11** [qwopqwop200/AutoQuant#2]
![image](https://github.com/qwopqwop200/AutoQuant/assets/3581877/6742f542-cc3e-4853-b0fd-693b1fcaaad9)
When I try to quantize llama7b and llama13b on A100 40GB, I got OOM.  It seems has gpu memory issue?
Another question is:  will this AutoQuant generate AWQ and GPTQ quantized weight in the same shape and format? Can I use same cuda kernel for inference?

**Comment by qwopqwop200** [comment]
AWQ quantization code is based on AutoAWQ. And AutoAWQ tends to quantize in an inefficient way compared to AutoGPTQ, so it requires relatively more memory. One solution is to reduce the number of `n_samples`.
`get_calib_dataset(tokenizer, 'pile',n_samples=64)`
GPTQ and AWQ are saved in the same format. Therefore, it is possible to use the same cuda kernel and is already doing so.

**Comment by wenqf11** [comment]
@qwopqwop200 https://github.com/PanQiWei/AutoGPTQ/issues/136#issuecomment-1580770892 Thanks for your reply. I need to generate AWQ quantized weight in the format  like GTPQ. You mentioned that this project(https://github.com/qwopqwop200/llm-awq) can do it. Is there any way I get this project?

**Comment by qwopqwop200** [comment]
Unfortunately. I remove it.
